import React from "react";
import { Dimensions, FlatList, Image, StyleSheet, View, Text } from "react-native";
// Generated by export.py after training — maps class ID string → array of require()'d images
import { THUMBNAILS } from "../services/thumbnails-index";
import { useTheme } from "../theme";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
const ITEM_WIDTH = SCREEN_WIDTH - 32;

interface Props {
  classId: string;
}

export function ThumbnailGallery({ classId }: Props) {
  const sources: number[] = THUMBNAILS[classId] ?? [];
  const theme = useTheme();

  if (sources.length === 0) {
    return (
      <View
        style={[styles.placeholder, { backgroundColor: theme.thumbnailPlaceholder }]}
      >
        <Text style={[styles.placeholderText, { color: theme.textSubtle }]}>
          No reference photos available
        </Text>
      </View>
    );
  }

  return (
    <FlatList
      data={sources}
      keyExtractor={(_, i) => String(i)}
      horizontal
      pagingEnabled
      showsHorizontalScrollIndicator={false}
      snapToInterval={ITEM_WIDTH}
      decelerationRate="fast"
      renderItem={({ item }) => (
        <Image
          source={item}
          style={[styles.image, { backgroundColor: theme.thumbnailPlaceholder }]}
          resizeMode="cover"
        />
      )}
    />
  );
}

const styles = StyleSheet.create({
  image: {
    width: ITEM_WIDTH,
    height: 260,
    borderRadius: 10,
  },
  placeholder: {
    width: ITEM_WIDTH,
    height: 260,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  placeholderText: {
    fontSize: 14,
  },
});
